### ISSUE TITLE
[Feat] Develop ansible module for reporting inventory for VM

### ISSUE THREAD

**Issue by ntnx-alexlee** [nutanix/nutanix.ansible#145]
Requirements:
- list of VM inventory with informaton including VM name, vcpu, memory, disk allocated, IP addresses, guest OS and Mac address. 
- Support both vmware and AHV on Nutanix

**Comment by bhati-pradeep** [comment]
Released in [v1.0.0-beta.1](https://github.com/nutanix/nutanix.ansible/releases/tag/v1.0.0-beta.1)
PR: https://github.com/nutanix/nutanix.ansible/pull/45
Although for extra information of vms, use ntnx_vms_info module
