### ISSUE TITLE
Cleanup documentation.

### ISSUE THREAD

**Issue by MohyedeenN** [nutanix/nutanix.ansible#27]
Remove operations, data. 
Add auth suboptions. 

Add mutual execlusive for subnet_name, subnet uuid in docs.

**Comment by bchristianv** [comment]
README incorrectly states inventory plugin is `ncp_prism_vm_inventory` but it is `ntnx_prism_vm_inventory`. At least that is the value needed for `plugin` in the inventory configuration when using it ;)
