### ISSUE TITLE
[Imprv] Make changes to include vm name and categories mapping in resources

### ISSUE THREAD

**Issue by Gevorg-Khachatryan-97** [nutanix/nutanix.ansible#274]
Make changes in `ntnx_prism_vm_inventory.py` to include vm name and categories mapping from `"metadata"` in vm information and set variable to have ability use those values to create groups.

https://github.com/nutanix/nutanix.ansible/blob/b82b58d0a767e821f64107c2f363cebfaa892822/plugins/inventory/ntnx_prism_vm_inventory.py#L174

**Comment by bhati-pradeep** [comment]
Usecase:
Can create custom groups based on category and vm name (expressions) using constructed inventory feature : #235

**Comment by bhati-pradeep** [comment]
As v1.7 is approaching, moving this out of it and will consider it in next release

**Comment by bhati-pradeep** [comment]
https://github.com/nutanix/nutanix.ansible/pull/405 This will add categories mapping in inventory

**Comment by george-ghawali** [comment]
This issue is resolved and closed. The fix has been merged via the PR linked in this issue. VM names and categories are now handled correctly, and groups can be created as expected. Thank you for reporting!
