### ISSUE TITLE
[Bug] <adding extra disks to existing VM causes new VM's to be created> in module <ntnx_vms>

### ISSUE THREAD

**Issue by stesnape** [nutanix/nutanix.ansible#275]
**Describe the bug**

**To Reproduce**
1. ansible command 
2. ntnx_vms
3. sample playbook used
  - name: VM add disks
    nutanix.ncp.ntnx_vms:
      name: VM_name
      validate_certs: False
      cluster:
        name: "CLUSTER
      disks:
        - type: "DISK"
          size_gb: 1
          bus: "SCSI"

**Stack trace**

**Expected behavior**
I'd expect this to add a new disk to an existing VM is already present.

Instead you get a new VM with the disk added 

**Additional context**
you could argue its a NTX feature as NTX isnt bothered about unique VM names and only with uuid's 
but there should be option to say use existing VM with that name.

only way i can get this to work as expected it to add disks using the vm_uuid rather than VM name
    nutanix.ncp.ntnx_vms:
      vm_uuid: 550032e8-c26a-4a37-adf6-eb7d3f112741

**Comment by bhati-pradeep** [comment]
Similar issue, you can find a explanation here. https://github.com/nutanix/nutanix.ansible/issues/284#issuecomment-1259267264
