### ISSUE TITLE
 ntnx_images: uploaded image  size shows empty in Prism central

### ISSUE THREAD

**Issue by sivaxsan** [nutanix/nutanix.ansible#355]
**Describe the bug**
Uploaded image  from local workstation size shows empty in prism central ; but if I upload the image via prism central GUI - it shows correct image size.

Note:  Image has been created via redhat image builder

**To Reproduce**
---
- name: Get Image
  hosts: localhost
  gather_facts: no
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ cluster_url }}"
      nutanix_username: "{{ prism_user }}"
      nutanix_password: "{{ prism_password }}"
  vars_files: nutanix_vars.yml
  tasks:
    - name: List images using name filter criteria
      nutanix.ncp.ntnx_images:
        state: "present"
        source_path: "/var/tmp/7f7bfb3a-6775-4e5a-b5f2-cc648ad77e77-disk.qcow2"
        validate_certs: False
        clusters:
          - name: "******"
        categories:
          AppFamily:
            - Backup
        name: "rhel_8_test_4"
        desc: "description"
        image_type: "DISK_IMAGE"
        wait: true
      register: result

    - name: print value
      debug:
        msg: '{{ result }}'

**Stack trace**

**Expected behavior**
image upload with correct image  size .

**Additional context**

**Comment by sivaxsan** [comment]
![Capture_error](https://user-images.githubusercontent.com/35259318/232010582-dd0041ae-e4bc-407a-8b1b-8c1ae2ba90cf.PNG)

**Comment by sivaxsan** [comment]
tried alternate option for source.

using source_uri:   
but getting
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "INTERNAL_ERROR: ImageCreate failed. HCI-DBA-UK2 - Could not access the URL https://162.11.33.2/build/RedHat/8/images/rhel-8.7-x86_64-kvm.qcow2: Peer's certificate issuer has been marked as not trusted by the user.. HCI-GEN-PRD-UK2 - Could not access the URL https://162.11.33.2/build/RedHat/8/images/rhel-8.7-x86_64-kvm.qcow2: Peer's certificate issuer has been marked as not trusted by the user.. HCI-VDI-STD-UK2 - Could not access the URL https://162.11.33.2/build/RedHat/8/images/rhel-8.7-x86_64-kvm.qcow2: Peer's certificate issuer has been marked as not trusted by the user.. HCI-SWG-SL2 - Could not access the URL https://162.11.33.2/build/RedHat/8/images/rhel-8.7-x86_64-kvm.qcow2: Peer's certificate issuer has been marked as not trusted by the user..

**Comment by sivaxsan** [comment]
my code:
   - name: List images using name filter criteria
      nutanix.ncp.ntnx_images:
        state: "present"
        source_uri: "https://162.11.33.2/build/RedHat/8/images/rhel-8.7-x86_64-kvm.qcow2"
        validate_certs: false
        name: "rhel_8_test_4"
        desc: "description"
        image_type: "DISK_IMAGE"
        wait: true
      register: result

**Comment by bhati-pradeep** [comment]
hi @sivaxsan, can you share Prism Central and Nutanix Ansible version you are using ? I can check.

**Comment by bhati-pradeep** [comment]
Hi @sivaxsan, Can you share response of playbook task once task finishes. You can mask sensitive details.
I tried in my local and it works fine for me. Wanted to check size attribute in response. Thanks.

**Comment by bhati-pradeep** [comment]
Also it size never comes in the UI or it comes after some time ?

**Comment by sivaxsan** [comment]
Image size never comes shows in the UI.   I couldn't use public  github in my office laptop.  so, it is difficult to update the logs.  Also,  playbook doesn't shows  any errors and it completed successfully.

As I observed,  couldn't see any issues , if I use RESTAPI and able to see the image size and use it for OS build.

nutanix.ncp.ntnx_images:  :  plays shows successful, but doesn't show image size and couldn't able to use it for OS build.

**Comment by bhati-pradeep** [comment]
Are you able to create image for VM deployment ?

**Comment by bhati-pradeep** [comment]
If you can print result of task. Check you check response.status.resources.size_bytes is set or not.

**Comment by sivaxsan** [comment]
Hi,  response.status.resources shows only below options:

 resources: {
   architecture: x86_84
   image_type: DISK IMAGE
}
state : Complete

I couldn't see size_bytes in the output

**Comment by bhati-pradeep** [comment]
hi @sivaxsan, Can you create nutanix support ticket ? This might need a call for for more debugging.

**Comment by sivaxsan** [comment]
I already raised a case with Nutanix, they advised to raise a issue in nutanix.ansible git repo.  Nutanix case: 01435754 [As they mentioned :  Issue relates open source project actively maintained by Nutanix, and will get support directly from github

**Comment by bhati-pradeep** [comment]
Okay. Let me get back to you, will try to reproduce on my local setup.

**Comment by bhati-pradeep** [comment]
Closing this ticket due to inactivity. Please reopen if you face it again.
