### ISSUE TITLE
[Bug] InvalidArgument: VLAN identifier has to be unique within managed networks on one Virtual Switch" in module ntnx_subnets

### ISSUE THREAD

**Issue by nx-sbourdeaud** [nutanix/nutanix.ansible#377]
**Describe the bug**
When adding a VLAN subnets with same VLAN ID (one is IPAM managed while the other is not), this works in the UI, but does not work with the ansible collection with the following error message: _InvalidArgument: VLAN identifier has to be unique within managed networks on one Virtual Switch"_

**To Reproduce**
1. create a VLAN subnet with id 100 and no ipam configuration: works
2. create a VLAN subnet with id 100 and an ipam configuration: fails

**Stack trace**

**Expected behavior**
Networks can have duplicate VLAN IDs, as long as one is IPAM managed while the other is not.

**Additional context**

**Comment by bhati-pradeep** [comment]
hi @nx-sbourdeaud , can you please share your playbook if possible ? I have tried this use case in my setup and it works fine.
My playbook:
```yml
 - name: "static vlan without ipam"
      ntnx_subnets:
        name: vlan_static
        vlan_subnet:
          virtual_switch:
            name: "<switch_name>"
          vlan_id: <vlan_id>
          cluster: 
            uuid: "<cluster_uuid>"
      register: result
  - debug:
        var: result
    
  - name: "static vlan with ipam"
      ntnx_subnets:
        name: vlan_static
        vlan_subnet:
          virtual_switch:
            name: "<switch_name>"
          vlan_id: <vlan_id>
          cluster: 
            uuid: "<cluster_uuid>"
          ipam:
            network_ip: "network_id"
            network_prefix: <network_prefix>
            gateway_ip: "<gateway_ip>"
            ip_pools:
              - start_ip: "<ip_start>"
                end_ip: "<ip_end>"
      register: result
  - debug:
        var: result

**Comment by bhati-pradeep** [comment]
Closing this ticket for now as its not reproducible in my setup. Please reopen if it happens again. Thanks
