### ISSUE TITLE
[Imprv] add functionality to support more filtering operators to module utils

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/nutanix.ansible#414]
**Describe the request**
Support other filtering operators than just `==`.

**Current behaviour**
You cannot pass any operator. The utils module uses under the covers `==` to concatenate the dictionary

**Expected behaviour**
Support other operators or even complex FIQL filters like this one `(platform_type!=aws,platform_type==[no_val]);power_state==on;is_cvm==0`

**Comment by bhati-pradeep** [comment]
Fixed in release v1.9.1
