### ISSUE TITLE
hard_poweroff has been moved to state from operation

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/nutanix.ansible#415]
The example in this file to power off a virtual machine doesn't work because hard_poweroff has been moved from operation to state.

https://github.com/nutanix/nutanix.ansible/blob/923e9c76915c55006882df6b0623ffb781ed854d/examples/vm_operations.yml#L23-L25

**Comment by bhati-pradeep** [comment]
Added in release v1.9.1
