### ISSUE TITLE
assign a category and value to an existing vm

### ISSUE THREAD

**Issue by dleanes** [nutanix/nutanix.ansible#487]
**Describe the bug**
A playbook was created that assigns a category and value to an already existing vm but it gives message 422 due to how the category entity is being added, I have checked and how I am doing it is how it should be added, but it continues with message 422 I created a case to nutanix support and they asked me to open a case here

**To Reproduce**
2.  attached  file  asigncategtovm.txt
[asigncategtovm.txt](https://github.com/user-attachments/files/16362722/asigncategtovm.txt)

error message 
 
msg": "Failed fetching URL: https://iaxxxxxxxx.es.mgmt.xxxxxxx.com:9440/api/nutanix/v3/vms/3efec4d5-9111-42c5-b12b-1f9148485d36",
    "response": null,
    "status_code": 422

log cvm nutanix 
024-07-24T12:42:06.530Z] "PUT /api/nutanix/v3/vms/3efec4d5-9111-42c5-b12b-1f9148485d36 HTTP/1.1" 422 - 4483 349 208 208 "172.30.178.19" "ansible-httpget" "xxxxxxx-xxx-xxx-xxxx" "172.xx.xxxx.xx" "172.xx.xxxx.xx:9444"
**Expected behavior**
I  need to add the categories to the vm and it can be seen in the prism central
[asigncategtovm.txt](https://github.com/user-attachments/files/16362708/asigncategtovm.txt)

**Comment by stahnjones** [comment]
did you try the new_categories as a list instead of a string?

  vars:
    new_categories:
      "Disaster_Recovery": 
        - value_L1_DR

**Comment by dleanes** [comment]
Hi, yes I probé and messages is: HTTP: Error BAD REQUEST

**Comment by dleanes** [comment]
Hi sorry, test again because iI put name of the vm wrong, I test name
correct y restult is succesfull .
Leave as stay with bar

Vars
Category_key: "{{ category_key }}"
Category_value: "{{ category_value}}"

Categories: "{{ { (category_key): [category_value]  } }}"

Thank you for you help

**Comment by george-ghawali** [comment]
Since it is working fine for the reporter, as well as I also checked. Hence, closing this ticket.
