### ISSUE TITLE
[Bug] Module ntnx_vms tries to access non existent endpoint 

### ISSUE THREAD

**Issue by EdenCore** [nutanix/nutanix.ansible#496]
Example playbook :
---
- name: VM playbook
  hosts: localhost
  gather_facts: false
  collections:
  - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ pc_ip }}"
      nutanix_username: "{{ nutanix_user }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: false
  tasks:
  - name: create Vm
    tags: "create_vm"
    ntnx_vms:
      state: present
      name: "ansible"
      desc: "description"
      categories:
        Environment:
          - "dev"
      cluster:
        name: "LAB"
      networks:
        - is_connected: True
          subnet:
            uuid: "{{ subnet_uuid }}"
      disks:
        - type: "DISK"
          size_gb: 30
          bus: "SATA"
          storage_container:
            name: "SelfServiceContainer"
      vcpus: 1
      cores_per_vcpu: 1
      memory_gb: 1

**Stack trace**
{
  "status_code": 500,
  "error": "HTTP Error 500: INTERNAL SERVER ERROR",
  "response": null,
  "msg": "Failed fetching URL: https://10.0.0.1:9440/api/nutanix/v3/groups",
  "invocation": {
    "module_args": {
      "nutanix_host": "10.0.0.1",
      "nutanix_username": "user1",
      "nutanix_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "validate_certs": false,
      "state": "present",
      "name": "ansible",
      "desc": "description",
      "categories": {
        "Environment": [
          "dev"
        ]
      },
      "cluster": {
        "name": "LAB"
      },
      "networks": [
        {
          "is_connected": true,
          "subnet": {
            "uuid": "HIDDEN"
          }
        }
      ],
      "disks": [
        {
          "type": "DISK",
          "size_gb": 30,
          "bus": "SATA",
          "storage_container": {
            "name": ""
          }
        }
      ],
      "vcpus": 1,
      "cores_per_vcpu": 1,
      "memory_gb": 1,
      "nutanix_port": "9440",
      "wait": true,
      "timezone": "UTC",
      "force_power_off": false,
      "remove_categories": false
    }
  },
  "_ansible_no_log": false,
  "changed": false
}

**Additional context**
Using the REST API Explorer v3.1.0 in Prism Central I noticed that there is no endpoint named "/groups".

**Comment by bhati-pradeep** [comment]
Can you share the PC version used ?

**Comment by bhati-pradeep** [comment]
Groups API we use it for fetching storage container uuid from storage container name. I can see that groups API works as expected for pc.2024.3.

1. your api failed for Internal error 500. It seems to be some api issue. If possible can you check PC logs for more details.
2.Can you try running this API for your setup incase its failing for you or not.
https://<pc-i[>:9440/api/nutanix/v3/groups
```json
{
    "entity_type": "storage_container",
    "filter_criteria": "container_name==SelfServiceContainer"
}
```

**Comment by EdenCore** [comment]
Hi, thanks for the update. I have not been able to reproduce the error. Furthermore, we upgraded Prism Central since the initial post. I think we should close this thread.
